#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : linux-steam-integration
Version  : 9759e21ee379ca2f7c6a267b95c76e0e68dc724e
Release  : 24
URL      : https://github.com/getsolus/linux-steam-integration/archive/9759e21ee379ca2f7c6a267b95c76e0e68dc724e.tar.gz
Source0  : https://github.com/getsolus/linux-steam-integration/archive/9759e21ee379ca2f7c6a267b95c76e0e68dc724e.tar.gz
Source1  : https://github.com/intel/libnica/archive/8ec3cf22916d3cd2dd4761576ef732c04b67277e.tar.gz
Summary  : Common C library functions
Group    : Development/Tools
License  : LGPL-2.1
Requires: linux-steam-integration-bin = %{version}-%{release}
Requires: linux-steam-integration-data = %{version}-%{release}
Requires: linux-steam-integration-lib = %{version}-%{release}
Requires: linux-steam-integration-license = %{version}-%{release}
Requires: linux-steam-integration-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32check)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(gtk+-3.0)

%description
# linux-steam-integration
## About
Linux Steam* Integration is a helper system to make the Steam Client and Steam
games run better on Linux. In a nutshell, LSI automatically applies various workarounds
to get games working, and fixes long standing bugs in both games and the client.

%package bin
Summary: bin components for the linux-steam-integration package.
Group: Binaries
Requires: linux-steam-integration-data = %{version}-%{release}
Requires: linux-steam-integration-license = %{version}-%{release}

%description bin
bin components for the linux-steam-integration package.


%package data
Summary: data components for the linux-steam-integration package.
Group: Data

%description data
data components for the linux-steam-integration package.


%package lib
Summary: lib components for the linux-steam-integration package.
Group: Libraries
Requires: linux-steam-integration-data = %{version}-%{release}
Requires: linux-steam-integration-license = %{version}-%{release}

%description lib
lib components for the linux-steam-integration package.


%package lib32
Summary: lib32 components for the linux-steam-integration package.
Group: Default
Requires: linux-steam-integration-data = %{version}-%{release}
Requires: linux-steam-integration-license = %{version}-%{release}

%description lib32
lib32 components for the linux-steam-integration package.


%package license
Summary: license components for the linux-steam-integration package.
Group: Default

%description license
license components for the linux-steam-integration package.


%package locales
Summary: locales components for the linux-steam-integration package.
Group: Default

%description locales
locales components for the linux-steam-integration package.


%prep
%setup -q -n linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e
cd ..
%setup -q -T -D -n linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e -b 1
mkdir -p src/libnica
cp -r %{_topdir}/BUILD/libnica-8ec3cf22916d3cd2dd4761576ef732c04b67277e/* %{_topdir}/BUILD/linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e/src/libnica
pushd ..
cp -a linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571416995
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dwith-steam-binary=/usr/bin/steam -Dwith-new-libcxx-abi=true -Dwith-frontend=true  builddir
ninja -v -C builddir
pushd ../build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Dwith-steam-binary=/usr/bin/steam -Dwith-new-libcxx-abi=true -Dwith-frontend=true -Dwith-shim=none -Dwith-new-libcxx-abi=true -Dwith-frontend=false builddir
ninja -v -C builddir
popd

%install
mkdir -p %{buildroot}/usr/share/package-licenses/linux-steam-integration
cp %{_builddir}/linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e/LICENSE %{buildroot}/usr/share/package-licenses/linux-steam-integration/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/linux-steam-integration-9759e21ee379ca2f7c6a267b95c76e0e68dc724e/src/libnica/LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/linux-steam-integration/01a6b4bf79aca9b556822601186afab86e8c4fbf
pushd ../build32
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang linux-steam-integration

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsi-exec
/usr/bin/lsi-settings
/usr/bin/steam

%files data
%defattr(-,root,root,-)
/usr/share/applications/lsi-settings.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblsi-intercept.so
/usr/lib64/liblsi-redirect.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/liblsi-intercept.so
/usr/lib32/liblsi-redirect.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/linux-steam-integration/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files locales -f linux-steam-integration.lang
%defattr(-,root,root,-)

